language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
<<<<<<< HEAD
  - docker-compose up -d
=======
  - docker-compose run app sh -c "python app.py tests"
>>>>>>> master
